package pl.septicwolf818.calltamer.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF1B813E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFA7F5B9)
val LightOnPrimaryContainer = Color(0xFF00210C)
val LightSecondary = Color(0xFF4E6352)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD1E9D3)
val LightOnSecondaryContainer = Color(0xFF0C1F12)
val LightTertiary = Color(0xFF3A646F)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFF6FBF4)
val LightOnBackground = Color(0xFF1A1C1A)
val LightSurface = Color(0xFFF6FBF4)
val LightOnSurface = Color(0xFF1A1C1A)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

val DarkPrimary = Color(0xFF8CD89E)
val DarkOnPrimary = Color(0xFF003919)
val DarkPrimaryContainer = Color(0xFF00532B)
val DarkOnPrimaryContainer = Color(0xFFA7F5B9)
val DarkSecondary = Color(0xFFB5CCB7)
val DarkOnSecondary = Color(0xFF213426)
val DarkSecondaryContainer = Color(0xFF374B3C)
val DarkOnSecondaryContainer = Color(0xFFD1E9D3)
val DarkTertiary = Color(0xFF93CCD9)
val DarkOnTertiary = Color(0xFF1E3540)
val DarkBackground = Color(0xFF1A1C1A)
val DarkOnBackground = Color(0xFFE2E3DF)
val DarkSurface = Color(0xFF1A1C1A)
val DarkOnSurface = Color(0xFFE2E3DF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
